version: '3.9'
services:
    notion-books:
        image: allaboutduncan/notion-isbn:latest
        container_name: notion-books
        restart: always
        ports:
            - '3331:3331'
        environment:
            - USE_AWS=yes/no
            - AWS_ACCESS_KEY_ID=ENTER-YOUR-ACCESS-KEY-HERE
            - AWS_SECRET_ACCESS_KEY=ENTER-YOUR-SECRET-KEY-HERE
            - AWS_BUCKET=bucket-name
            - NOTION_TOKEN=notion_secret
            - NOTION_DATABASE_ID=notion-database-id
            - GoogleAPIKey=Google-Books-API-Key
            - USE_PUSHBULLET=yes/no
            - PB_TOKEN=pushbullet_access_token